name: Continuous Integration

on:
  schedule:
    # This example triggers the workflow every day at 5:30 UTC:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache dependencies
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: ${{ runner.tool_cache }}/Python/3.10.13 # e.g /opt/hostedtoolcache/Python/3.11.6
          key: ${{ runner.tool_cache }}/Python/3.10.13/${{ runner.arch }}-${{ hashFiles('requirements.txt') }}
      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.13'
      - name: Install pip dependencies
        shell: bash
        run: pip install -r test_requirements.txt
      - uses: actions/cache/save@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ runner.tool_cache }}/Python/3.10.13 # e.g /opt/hostedtoolcache/Python/3.11.6
          key: ${{ runner.tool_cache }}/Python/3.10.13/${{ runner.arch }}-${{ hashFiles('requirements.txt') }}
        
      - name: Export to csv
        run: python df_to_csv.py  
        
      # - name: Commit data files
      #   run: |
      #     git config --global user.name 'manan145'
      #     git config --global user.email 'mananjagani145@gmail.com'
      #     git add web_scraped_data.csv
      #     git commit -m "saving new data"
      #     git push


      - name: Backup of data files
        uses: actions/upload-artifact@v4
        with:
          name: Backup_data
          path: |
            cleaned_data.xlsx
            cleaned_data.json
            cleaned_data.db
